#!/bin/bash

# Copyright 2018 Northern.tech AS
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

application_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
output_dir=${MENDER_CONVERSION_OUTPUT_DIR:-${application_dir}}/output

set -e

function cleanup {
    if mount | grep -q output/rootfs; then
        sudo umount ${output_dir}/rootfs
    fi
}
trap cleanup EXIT

usage() {
cat << EOF
Usage: $(basename $0) options (:hc:d:i:m:n:o:s:t:R:)
    -c - Server certificate (Only for Mender Production setup)
    -D - Data partition size in MB
    -d - Device type (/data/mender/device_type)
    -i - Path to image to convert
    -m - Path to Mender client binary
    -n - Mender artifact_name (/etc/mender/artifact_name)
    -o - Demo mode, takes demo server IP address as an argument
    -s - Server URL (Only for Mender Production setup)
    -S - Swap partition size in MB
    -t - File containing Hosted Mender token (Hosted Mender mode)
    -R - Root file-system partition size in MB
    -p - Platform (currently either rpi-ubuntu or pc-ubuntu)
    -h - Prints this text
EOF
    exit 1
}

# Prompt the user for a yes/no answer
# default to "no"
promptYN() {
    local prompt="$1"
    printf "%s" "$prompt" >&2 && read yn
    case $yn in
        [Yy]* ) echo "y";;
        *     ) echo "n";;
    esac
}

mender_rootfs_part_size_mb=1024
mender_data_part_size_mb=256
mender_swap_part_size_mb=0
mender_platform="rpi-ubuntu"

[ $# -eq 0 ] && usage

while getopts ":hc:d:D:i:m:n:o:p:s:S:t:R:" arg; do
    case $arg in
    c) # Mender Production server certificate
        mender_production_cert=${OPTARG}
        echo "Mender Production certificate: ${mender_production_cert}"
        ;;
    d) # Device type
        device_type=${OPTARG}
        echo "Device type: ${device_type}"
        ;;
    D) # Data partition size
        mender_data_part_size_mb=${OPTARG}
        echo "Data partition size (MB): ${mender_data_part_size_mb}"
        ;;
    i) # Path to image
        image_to_convert=${OPTARG}
        echo "Image to convert: ${image_to_convert}"
        ;;
    n) # Mender artifact name
        artifact_name=${OPTARG}
        echo "Mender artifact name: ${artifact_name}"
        ;;
    m) # Path to Mender client binary
        mender_binary=${OPTARG}
        echo "Path to Mender client binary: ${mender_binary}"
        ;;
    o) # Demo server IP address
        mender_demo_ip=${OPTARG}
        echo "Mender demo server IP: ${mender_demo_ip}"
        ;;
    p) # Platform
        mender_platform=${OPTARG}
        echo "Mender Platform: ${mender_platform}"
        ;;
    s) # Server URL
        mender_production_url=${OPTARG}
        echo "Mender Production URL: ${mender_production_url}"
        ;;
    S) # Swap partition size
        mender_swap_part_size_mb=${OPTARG}
        echo "Swap partition size (MB): ${mender_swap_part_size_mb}"
        ;;
    t) # Hosted Mender token
        mender_hosted_token=${OPTARG}
        echo "Hosted Mender token: ${mender_hosted_token}"
        ;;
    R) # Root filesystem size
        mender_rootfs_part_size_mb=${OPTARG}
        echo "Root file-system partition size (MB): ${mender_rootfs_part_size_mb}"
        ;;
    h | *) # Display help.
        usage
        ;;
    esac
done

if [ -z "$artifact_name" ] || [ -z "$image_to_convert" ] || \
    [ -z "$mender_binary" ] || [ -z "$device_type" ]; then
    usage
fi

if [ ! -e ${mender_binary} ]; then
    echo "${mender_binary}: can not be found"
    exit 1
fi

case ${mender_platform} in
    "rpi-ubuntu" )
        mender_image_alignment="24576"
        mender_rootfsA="/dev/mmcblk2"
        mender_rootfsB="/dev/mmcblk3"
        ;;

    "pc-ubuntu" )
        mender_image_alignment="2048"
        mender_rootfsA="/dev/sda2"
        mender_rootfsB="/dev/sda3"
        ;;

    * )
        echo "Error.  Unrecognized platform ${mender_platform}"
        usage
        ;;
esac

stage_2_args="-a ${artifact_name} -d ${output_dir}/data -m ${mender_binary} \
    -r ${output_dir}/rootfs -t ${device_type} -A ${mender_rootfsA} -B ${mender_rootfsB}"

if [ -n "${mender_hosted_token}" ]; then
    stage_2_args="${stage_2_args} -T ${mender_hosted_token}"
fi

if [ -n "${mender_production_cert}" ]; then
    stage_2_args="${stage_2_args} -c ${mender_production_cert} -s ${mender_production_url}"
fi

if [ -n "${mender_demo_ip}" ]; then
    stage_2_args="${stage_2_args} -o ${mender_demo_ip}"
fi

if [ -d ${output_dir} ]; then
    [ "$(promptYN "Warning. ${output_dir} already exists and will be overwritten. OK? ")" = "y" ] || exit 0
fi

${application_dir}/convert-stage-1.sh ${image_to_convert}

mkdir -p ${output_dir}/data

eval set -- " ${stage_2_args}"

${application_dir}/convert-stage-2.sh ${stage_2_args}

${application_dir}/convert-stage-3.sh
${application_dir}/convert-stage-4.sh ${mender_swap_part_size_mb} ${mender_platform}
${application_dir}/convert-stage-99.sh ${mender_rootfs_part_size_mb} ${mender_data_part_size_mb} ${mender_swap_part_size_mb} ${mender_image_alignment} ${mender_platform}

cleanup

